
services:
  app:
    build: .
    init: true
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    volumes:
      - mongo_volume:/data/db
  
volumes:
  mongo_volume: